# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vitalii Tsilnyk
description: ~
header_pages:
  - blog/index.html
  - about.html
  - contact.html
head_assets:
  css:
      - '/assets/vendor.bundle.css'
      - '/assets/app.bundle.css'
  js:
      - '/assets/vendor.bundle.js'
      - '/assets/app.bundle.js'

# Contacts
contacts:
  email: ~
  github_username: VitaliiTsilnyk
  keybase_username: vitaly_zilnik

# External services
google_analytics: ~
disqus:
  enabled: true
  shortname: ~
formcarry:
    form_key: q3VGtpycXUQ

# Blog settings
show_excerpts: true
#excerpt_separator: <!--more-->

collections:
  posts:
    output: true
    permalink: /blog/:categories/:title/

# Build settings
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
markdown: kramdown
#theme: minima
paginate: 1
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
 - .idea/
 - README.md
 - Gemfile
 - Gemfile.lock
 - node_modules
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
 - package.json
 - package-lock.json
 - postcss.config.js
 - webpack.config.js
